### ISSUE TITLE
Link to Trello board is not working

### ISSUE THREAD

**Issue by reinier** [bachya/pinpress#1]
The link to the PinPress Trello board mentioned in [Bugs and Feature Requests](https://github.com/bachya/pinpress#bugs-and-feature-requests) is not available on Trello.

**Comment by bachya** [comment]
Just clicked on that link and it took me to the board:

![screen shot 2015-06-01 at 2 51 47 pm](https://cloud.githubusercontent.com/assets/47216/7923084/ca7db92e-086d-11e5-99ab-5a00e2f28641.png)

The board is public-access, too, so it should be visible.

**Comment by reinier** [comment]
Unfortunately, it's not working for me. See screenshot.

![screen shot 2015-06-02 at 13 45 41](https://cloud.githubusercontent.com/assets/6823/7935054/bf50cf4e-092d-11e5-8fdb-82b9b2b0e46e.png)

Is this the correct url? https://trello.com/b/lmuC8TT0/pinpress

**Comment by bachya** [comment]
I've messed with the permissions a bit more. Try one more time?

**Comment by reinier** [comment]
It's working now, thanks!
